version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  doctor-service:
    build: ./apps/doctor-service
    depends_on:
      - postgres

  patient-service:
    build: ./apps/patient-service
    depends_on:
      - postgres

  visit-service:
    build: ./apps/visit-service
    depends_on:
      - postgres

  note-service:
    build: ./apps/note-service
    depends_on:
      - postgres

  news-service:
    build: ./apps/news-service
    depends_on:
      - postgres

  api-gateway:
    build: ./apps/api-gateway
    depends_on:
      - doctor-service
      - patient-service
      - visit-service
      - note-service
      - news-service

volumes:
  pgdata:
