version: "3.9"

services:
  doctor-service:
    build: ./doctor-service
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/doctor_db

  patient-service:
    build: ./patient-service
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/patient_db

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - doctor-service
      - patient-service

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  